### ISSUE TITLE
support Canon CR3 files

### ISSUE THREAD

**Issue by catdad** [catdad/raw-viewer#110]
`exiftool` v10.53 seems to have some issues with cr3... which makes sense, that version came out before cr3 was even a thing. The latest v11.32 seems to do much better at this, but it looks like `dist-exiftool` is not being updated anymore... :(

- [x] view image
- [x] assign rating
- [x] handle rotation
- [x] fix issue with slow rendering

**Comment by catdad** [comment]
For reference:
* https://github.com/Sobesednik/node-exiftool.exe/pull/6/files
* https://github.com/Sobesednik/node-exiftool.pl/pull/6

**Comment by catdad** [comment]
There seems to be an issue with getting the full meta:

![image](https://user-images.githubusercontent.com/2205537/54968826-657b4200-4f52-11e9-80c4-e129348a9466.png)

`exiftool` seems to get the meta quite fast, on par with all other images, yet somehow, the sidebar timing (and user timing) is quite slow.

**Comment by catdad** [comment]
The size of the embedded image in CR3 files are pretty much the whole size of the image? Interesting. Anyway, passing it through `sharp` shrinks it down to an expected jpeg size.

![image](https://user-images.githubusercontent.com/2205537/55293024-4996f680-53bf-11e9-99d8-a65d6a190152.png)

**Comment by Liberxue** [comment]
![image](https://user-images.githubusercontent.com/5831248/66432497-c8e14300-ea50-11e9-8d97-30575b659643.png)

**Comment by catdad** [comment]
@Liberxue I have some CR3 files in my collection from an M50 and R, which work correctly. Are your files from a different camera? Would you mind sending me one of these files please?
