### ISSUE TITLE
question

### ISSUE THREAD

**Issue by catdad** [catdad/raw-viewer#222]

**Comment by Austinthemighty** [comment]
I would like to integrate this into a web based viewer for a portable file transfer device, is there an api that I can use, or what script/s would I need in order to view a raw image file on an html web page?

**Comment by catdad** [comment]
Well, Raw Viewer isn't an API or even a server that can provide any functionality to a web page. It also uses a lot of native code, so it really can't be used directory for a web page in the browser.

However, being able to open a raw image file in the browser is certainly doable. A raw image is, in simplified terms, a fancy TIFF file, so we really just need some tooling designed to work with it. Further, most raw images produced by a camera will contain, in addition to the raw data, an embedded jpeg image (which also happens to be the same jpeg that is created when you shoot in a RAW+JPEG mode). In the case of Raw Viewer, this jpeg image is what is shown to the user (Lightroom, similarly, displays this jpeg image by default, with an option for it to generate a different jpeg image on its own if you are willing to wait a while). [`exifreader`](https://github.com/mattiasw/ExifReader) can do this for you -- reading the `ArrayBuffer` for the raw image and providing access to the `ArrayBuffer` (or a base64 string) for the embedded jpeg. There is also a [`dcraw`](https://www.npmjs.com/package/dcraw) emscripten package, which can actually render the raw data itself rather than using the embedded jpeg. However, this package is quite large and very slow, and often creates images that look worse (dcraw never did strive for image quality).

How this helps!

**Comment by Austinthemighty** [comment]
ok, thanks for the info.  the main problem for me is when i shoot I turn off the jpeg duplicate to save space, as I do all of my work on the raw file.  I don't really care about the quality of the image as I'm just wanting a quick preview of the image, just to see if I got anything good or if the angle I was shooting at was good.
