### ISSUE TITLE
using sharp with electron 6

### ISSUE THREAD

**Issue by severussnape357** [catdad/raw-viewer#259]
hi, have you figured out how to use sharp with electron 6?
ive tried your raw viewer and it works great!
best 
paul

**Comment by catdad** [comment]
Please see #251 (it links to an issue in `sharp`). The developer of `sharp` already mentioned that pre-built binaries will already be included in the next release. In the meantime, all you have to do is compile it yourself. Or, if you are like me and are too lazy to figure out what is needed on each OS, you can just wait for the next release of `sharp`.

Is there a particular reason you are asking me this question?

**Comment by severussnape357** [comment]
i need the sharp converter for a similar project :)

**Comment by catdad** [comment]
I would suggest asking this in the `sharp` repo instead or checking out the build instructions here: https://sharp.pixelplumbing.com/en/stable/install/
